name: Validar mensajes de commits

on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias
        run: |
          npm install --save-dev @commitlint/{cli,config-conventional}

      - name: Validar commits
        run: |
          git fetch --depth=2 origin ${{ github.event.pull_request.base.ref }}
          commits=$(git log --format="%H" origin/${{ github.event.pull_request.base.ref }}..HEAD)
          for commit in $commits; do
            echo "🔍 Validando commit: $commit"
            git show -s --format=%B $commit | npx commitlint
          done
