name: Validar mensajes de commits

on:
  workflow_call:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependencias de commitlint
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Validar commits del pull request
        run: |
          git fetch --depth=2 origin ${{ github.event.pull_request.base.ref }}
          commits=$(git log --format="%H" origin/${{ github.event.pull_request.base.ref }}..HEAD)
          for commit in $commits; do
            echo "🔍 Validando commit: $commit"
            mensaje=$(git show -s --format=%B $commit)
            echo "$mensaje" | npx --no-install commitlint
          done
